### ISSUE TITLE
buildscripts 20151213 devkitPSP - binutils build fails

### ISSUE THREAD

**Issue by ali1234** [devkitPro/buildscripts#10]
```
../../../../binutils-2.22/bfd/doc/bfd.texinfo:325: unknown command `colophon'
../../../../binutils-2.22/bfd/doc/bfd.texinfo:336: unknown command `cygnus'
Makefile:421: recipe for target 'bfd.info' failed
make[3]: *** [bfd.info] Error 1
```

This seems to be a known issue in binutils, and fixed upstream.

https://sourceware.org/bugzilla/show_bug.cgi?id=15183
http://trac.clfs.org/ticket/926
... and lots more hits on Google, all with the same conclusion.

**Comment by WinterMute** [comment]
devkitPSP is no longer being maintained, sorry

**Comment by NHellFire** [comment]
I've fixed these issues in my fork: https://github.com/NHellFire/devkitpro-buildscripts
Tested working on Ubuntu 16.04.1 with GCC 5.4 and texinfo 6.1, unlikely to break older versions.
