### ISSUE TITLE
Building on Linux/Debian/Ubuntu 

### ISSUE THREAD

**Issue by lavanoid** [devkitPro/buildscripts#17]
I've been compiling DKP using this method:**[edit: remove link to incredibly bogus build instructions]** but after compiling for a while, it throws out errors. Is there any other dependencies that must be met for an "error-less" compile?

How have you been compiling DKP to run on Linux machines? I've been wanting to use DKP on ARM devices.

**Comment by mariogamer2** [comment]
What kind of error (building gcc,binutils,linking...) ?

**Comment by lavanoid** [comment]
Welp, I'm compiling on Ubuntu 15 x86_64 (to test compilation. Once I have managed successful compilation on this, I'll re-attempt on ARM. ARM devices take forever to compile this):

Here is my first error output:

`source/xm.c:646:84: warning: multi-character character constant [-Wmultichar]
  if( read32() != 'etxE' || read32() != 'dedn' || read32() != 'doM ' || read32() != ':elu' || read8() != ' ' )
                                                                                    ^
gcc     -o mmutil adpcm.o files.o gba.o it.o kiwi.o main.o mas.o mod.o msl.o nds.o s3m.o samplefix.o simple.o upload.o wav.o xm.o -lm 
make[1]: Entering directory '/home/lavanoid/Documents/buildscripts/.devkitARM/mmutil-1.8.6'
test -z "/opt/devkitpro/devkitARM/bin" || /bin/mkdir -p "/opt/devkitpro/devkitARM/bin"
  /usr/bin/install -c mmutil '/opt/devkitpro/devkitARM/bin'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/lavanoid/Documents/buildscripts/.devkitARM/mmutil-1.8.6'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether /usr/bin/make sets $(MAKE)... yes
checking whether /usr/bin/make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by /usr/bin/make... GNU
checking dependency style of gcc... none
checking for libusb_init in -lusb... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for USB... no
configure: error: *** Required libusb-1.0 >= 1.0.0 not installed ***
error configuring dfu-util-0.8.1.tar.bz2
`

**Comment by lavanoid** [comment]
Just installed libusb. Re-compiling

**Comment by WinterMute** [comment]
If you really, really followed those instructions then I highly recommend you format your system and reinstall it. Those are **awful**. You should **never** under **any** circumstances extract a random archive to / as root.

The instructions you should be following are in https://github.com/devkitPro/buildscripts/blob/master/README.TXT and you should use the released buildscripts rather than using the scripts from git. The scripts in git are often in progress to the next release and may require dependencies which currently only exist on developer machines.

Your current error is lack of libusb-dev.

**Comment by lavanoid** [comment]
I already have the mentioned packages installed, in the README.TXT. As for those archives mentioned in GBATemp, I'm not that idiotic and I haven't used them (although I have checked their contents).

Sorry for my ignorance but where is the released buildscripts?

**Comment by mariogamer2** [comment]
http://sourceforge.net/projects/devkitpro/files/buildscripts/

**Comment by lavanoid** [comment]
Ah I see. Thank you, both!

**Comment by nastys** [comment]
@WinterMute Don't worry, he doesn't have to format his system, since @lavanoid and I worked on that together. It wasn't initially meant to be published, but other people asked for it.

That archive doesn't contain a full devKitPro installation. I totally agree that building it is much better. I made it because my tablet could build it much faster than @lavanoid 's Raspberry Pi (if I recall correctly), so I just built it myself then sent him the compressed binaries.

**Comment by lavanoid** [comment]
New error:

    make[1]: Entering directory '/home/lavanoid/Downloads/buildscripts/.devkitARM/dfu-util-0.8.1'
    Making all in src
    make[2]: Entering directory '/home/lavanoid/Downloads/buildscripts/.devkitARM/dfu-util-0.8.1/src'
      CC     main.o
    In file included from main.c:34:0:
    portable.h:17:17: fatal error: io.h: No such file or directory
    compilation terminated.
    Makefile:334: recipe for target 'main.o' failed
    make[2]: *** [main.o] Error 1
    make[2]: Leaving directory '/home/lavanoid/Downloads/buildscripts/.devkitARM/dfu-util-0.8.1/src'
    Makefile:289: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/lavanoid/Downloads/buildscripts/.devkitARM/dfu-util-0.8.1'
    Makefile:229: recipe for target 'all' failed
    make: *** [all] Error 2
    error building dfu-util-0.8.1

**Comment by mariogamer2** [comment]
missing portable.h...

Googling this give me: https://github.com/winlibs/openldap/blob/master/include/portable.h

**Comment by lavanoid** [comment]
Are you sure portable.h is missing and not io.h?

**Comment by mariogamer2** [comment]
Not sure,you can try both.

**Comment by WinterMute** [comment]
@lavanoid

https://github.com/devkitPro/buildscripts/issues/2

dfu-util isn't necessary for 3DS, you can either ignore this for now & disable dfu-util building or use the patch from upstream. https://sourceforge.net/p/dfu-util/dfu-util/ci/861753401c3f6d4f2937294b5eb6133b0a583b0c/

**Comment by mariogamer2** [comment]
Didn't see'n the io.h,it is the missing file...

**Comment by lavanoid** [comment]
https://gist.github.com/lavanoid/c5559e24d4c7f12174e6b6d2ef620334

Had to paste the error in a gist, since I'm on mobile and I have nooo idea what's the best way of using markup  to show the error.

**Comment by carstene1ns** [comment]
@lavanoid: As the error states, you need the `makeinfo` program of the `texinfo` package.
Executing `# apt-get install texinfo` should make it available.

**Comment by lavanoid** [comment]
Ahh, sorry. I was half asleep when I read the error message (seems like I was so tired that I failed to recognise that part).

**Comment by lavanoid** [comment]
Installed the package "texinfo" but the same error still occurs.

**Comment by carstene1ns** [comment]
Well, a changed root does not really care if you install packages on the host system.
May I ask what you are even trying to accomplish there?

**Comment by lavanoid** [comment]
Huh? Everything I'm doing is taking place in a CHROOT environment, since I can't exactly install packages into Android...

I installed everything within the CHROOT. Honestly your question has confused me... I installed the package within the Kali CHROOT.

**Comment by lavanoid** [comment]
My main goal is to be able to use the DKP toolchains from within the CHROOT, on a mobile device that has an ARMv7 SoC.

**Comment by WinterMute** [comment]
Is this still an issue or did you succeed in building?
