### ISSUE TITLE
Please make this open source by adding a license

### ISSUE THREAD

**Issue by Midar** [devkitPro/buildscripts#20]
Currently, there is no license. While the compiler and the libraries have a license, the scripts and rules do not. This is a problem, as without a license, it is not possible to package this up for easy installation. As it is right now, no rights whatsoever are granted to use any of the files.

**Comment by mariogamer2** [comment]
Agree. Maybe GPL if you want open source fork and other,or the MIT license.

**Comment by WinterMute** [comment]
As the scripts state when run. "Please note, these scripts are provided as a courtesy, toolchains built with them are for personal use only and may not be distributed by entities other than devkitPro. See http://devkitpro.org/wiki/Trademarks"

No rights are granted for distribution of these scripts.

**Comment by Midar** [comment]
Am 8. September 2016 09:20:15 MESZ, schrieb Dave Murphy <notifications@github.com>:
> Closed #20.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/devkitPro/buildscripts/issues/20#event-781975850

Does that include the build rules used by many projects (e.g. 3ds_rules)? If that's the case, the community needs to move away from them as quickly as possible, as those projects cannot legally be built then.

-- 
Jonathan

**Comment by Midar** [comment]
Am 8. September 2016 09:20:15 MESZ, schrieb Dave Murphy <notifications@github.com>:
> Closed #20.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/devkitPro/buildscripts/issues/20#event-781975850

Same for the linker scripts. If you insist on granting no rights to those build rules and linker scripts, all software using devkitpro cannot be legally built, making it useless and necessary to create a replacement.

-- 
Jonathan

**Comment by WinterMute** [comment]
Not having rights to distribute these buildscripts or the binaries you build using them has no bearing on your right to build your own software using the tools we provide and does not prevent you distributing your own software.

**Comment by Midar** [comment]
Am 8. September 2016 11:47:17 MESZ, schrieb Dave Murphy <notifications@github.com>:
> Not having rights to distribute these buildscripts or the binaries you
> build using them has no bearing on your right to build your own
> software using the tools we provide and does not prevent you
> distributing your own software. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/devkitPro/buildscripts/issues/20#issuecomment-245548079

This is not true: The crt being linked is in this repository. So even the compiled binaries cannot be legally distributed.

Even if the crt were not part of this repository, then it would still be impossible to legally build software using this, as you have given no rights, not even to use them. The resulting binary might be unaffected, but the process of getting a binary would not legally be possible. IANAL, but I would guess that you also cannot legally distribute a binary if you could not legally build it. It's as if you would build a binary with a pirated Visual Studio and then distribute it.

-- 
Jonathan

**Comment by WinterMute** [comment]
What precisely is your use case here? What need do you have to package anything from this repository?

**Comment by Midar** [comment]
Am 8. September 2016 12:26:26 MESZ, schrieb Dave Murphy <notifications@github.com>:
> What precisely is your use case here? What need do you have to package
> anything from this repository?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/devkitPro/buildscripts/issues/20#issuecomment-245556983

I want to add devkitARM, PPC and PSP to pkgsrc. This would not use the shell scripts, but it would need to have the Makefile rules, linker scripts and crts. Those currently all don't have a license - and maybe should even be in a separate repository, as they are not really scripts to build devkitPro.

You already have a trademark on devkitPro, there's no reason to go even further by making sure all binaries built with it get tainted by linking in proprietary parts. What do you gain from that, except someone rewriting those parts and creating a competing toolchain because they want to use an open source toolchain?

-- 
Jonathan

**Comment by asiekierka** [comment]
Yes, a lot of package repositories for Linux or BSD require clearly filled out "license" fields. Gentoo, for example, requires you to personally agree to any license not considered FOSS. Debian requires license information *and* proof for the license being valid for a given version of the software.
