### ISSUE TITLE
Update of link in README.TXT#L62

### ISSUE THREAD

**Issue by gpadd** [devkitPro/buildscripts#21]
https://github.com/devkitPro/buildscripts/blob/devkitARM_r46/README.TXT#L57
The link should be updated to this: http://devkitpro.org/wiki/Getting_Started

Thank you all for the good work!

**Comment by gpadd** [comment]
Actually, this link should be updated in master too.
Thanks yet again.

**Comment by WinterMute** [comment]
It's actually a missing redirect after a server move. Fixed again.
