### ISSUE TITLE
build issue on macOS Sierra

### ISSUE THREAD

**Issue by nathanejohnson** [devkitPro/buildscripts#24]
I consistently got an error "Building with plugin support requires a host that supports dlopen" when compiling binutils 2.27 from your distribution. I was able to get everything to work by updating to 2.27.90 from upstream (I still have it apply your opcodes patch).

The good news is I appear to have a working 64 bit toolchain on Sierra.

Thanks for this excellent project!

**Comment by WinterMute** [comment]
Managed to pick up a cheap Macbook with El Capitan and I don't seem to have any real trouble getting this built with the Sierra SDK so I guess it's some issue with your setup. Personally I build the needed extras from source manually to avoid pulling in too many dependencies over & above a stock OSX install so it's possible that there's something I'm not encountering.

The good news you may like is that there are now official 64bit OSX binaries :)

The latest perl installers @ https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/ should grab the 64 bit binaries for you or you can grab the tarballs manually from https://sourceforge.net/projects/devkitpro/files/devkitPPC/ or https://sourceforge.net/projects/devkitpro/files/devkitARM/
