### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by cspencer49519** [devkitPro/buildscripts#25]
Hello, when I attempt to run the build script, I receive this error:

make[2]: Entering directory '/home/graffix/Downloads/buildscripts/.devkitARM/dfu-util-0.9.1/src'
  CC       main.o
In file included from main.c:36:0:
portable.h:32:3: error: #error "Can't get no sleep! Please report"
 # error "Can't get no sleep! Please report"
   ^
main.c: In function ‘main’:
main.c:430:3: warning: implicit declaration of function ‘milli_sleep’ [-Wimplicit-function-declaration]
   milli_sleep(status.bwPollTimeout);
   ^
Makefile:392: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
make[2]: Leaving directory '/home/graffix/Downloads/buildscripts/.devkitARM/dfu-util-0.9.1/src'
Makefile:349: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/graffix/Downloads/buildscripts/.devkitARM/dfu-util-0.9.1'
Makefile:289: recipe for target 'all' failed
make: *** [all] Error 2
error building dfu-util-0.9.1

Please advise.

**Comment by WinterMute** [comment]
Do the provided binaries not work on your system?

**Comment by cspencer49519** [comment]
They do not, here are my specs:
Linux Mint 18.1 Cinnamon 64-Bit

Linux wiiu-dev 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

When attempting to compile devkitproARM using the build script, I receive the error I documented.

**Comment by WinterMute** [comment]
What error do you get when you use the provided devkitARM binaries?

**Comment by PGAnonamous** [comment]
@cspencer49519 

I had this issue myself using the latest Xubuntu. I resolved it by extracting dfu-util-0.9.1.tar.bz2 to a folder and running autogen.sh. After that finishes just replace the files in the archive with the newly generated files and resume the build.

**Comment by WinterMute** [comment]
If there's an issue running the provided binaries on a debian based distro then I'd like to know what it is.

**Comment by PGAnonamous** [comment]
I believe it has to do with dfu-utils being generated with an older autoreconf. I'm not positive though and I'll have to check when I get out of class tonight.

**Comment by WinterMute** [comment]
That won't cause the provided **binaries** to fail. I want to know why the binaries fail on Mint - they **should** work fine there.

**Comment by PGAnonamous** [comment]
I must apologize I must have been thinking of a something else. I have encountered that from building it although I do not remember why. I just re-cloned the repository and built it without issue and cannot seem to recreate the issue.

**Comment by VinPaul** [comment]
I get the exact same error on a Raspberry Pi 3 Model B with Raspbian Jessie with PIXEL.

**Comment by WinterMute** [comment]
Since people keep commenting on this issue with "me too" type comments & then deleting them I can only assume that this is some kind of obvious user error.

The scripts are provided as a courtesy - we don't really have time to get into debugging build problems on other people's machines.
