### ISSUE TITLE
iostream fails to link on r46 with: undefined reference to `__sync_synchronize'

### ISSUE THREAD

**Issue by zeta0134** [devkitPro/buildscripts#26]
Greetings devkitPro team,

I thought for a while that I'd run into an esoteric bug with my project, but it seems this is more of a standard library issue with the newer GCC versions. For whatever reason, using iostream causes linker errors with devkitPro r46, and works fine with earlier revisions. The only other build I have lying around that works properly is r42, since my [PikminDS](https://github.com/zeta0134/pikmin-nds) project uses it.

I've attached the simplest possible example I could think of to reproduce the issue. Essentially, using iostream + cout compiles correctly as one might expect, but fails to link with the referenced error. Here's the full error output, I've attached a .zip file containing the full project folder. It's the example file from examples/nds/hello_world, modified to produce the error in question and stripped of everything non-essential.

```
$ make
main.cpp
arm-none-eabi-g++ -MMD -MP -MF /source/test/build/main.d -g -Wall -O2 -march=armv5te -mtune=arm946e-s -fomit-frame-pointer -ffast-math -mthumb -mthumb-interwork -I/source/test/include -I/source/test/build -I/opt/devkitPro/libnds/include -I/source/test/build -DARM9 -fno-rtti -fno-exceptions -c /source/test/source/main.cpp -o main.o
linking test.elf
/opt/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/lib/thumb/libstdc++.a(locale_init.o): In function `(anonymous namespace)::get_locale_mutex()':
(.text._ZN12_GLOBAL__N_116get_locale_mutexEv+0x6): undefined reference to `__sync_synchronize'
/opt/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/lib/thumb/libstdc++.a(locale.o): In function `std::locale::_Impl::_M_install_cache(std::locale::facet const*, unsigned int)':
(.text._ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEj+0x14): undefined reference to `__sync_synchronize'
collect2: error: ld returned 1 exit status
/opt/devkitPro/devkitARM/ds_rules:53: recipe for target '/source/test/test.elf' failed
make[1]: *** [/source/test/test.elf] Error 1
Makefile:94: recipe for target 'build' failed
make: *** [build] Error 2
```

I'm hoping there's something as simple as a compiler flag I can use in my project's makefile, but Google is not helping so far, I've tried a few things with no luck. Research suggests it's the standard library itself which needs to be recompiled without support for whatever it's trying to do with thread safety, but I won't pretend to be an expert on the subject.

This *seems* like the right place to report this, but if I'm mistaken my apologies, directions to the proper reporting location would be appreciated.
[iostream-bug-r46.zip](https://github.com/devkitPro/buildscripts/files/1045272/iostream-bug-r46.zip)

**Comment by WinterMute** [comment]
It's as good a place as any to report issues with the toolchains.

I can fix this relatively easily with r47 but for the time being you can add a stub function (`extern "C" void __sync_synchronize() {}` ) to your project to bypass the link error. The function is intended for thread safety which isn't really an issue with DS code currently.

It might be worth mentioning that iostream is a particularly heavy subsystem to be using on the DS given that it currently adds around 400K to your binary which is roughly 10% of the memory you have available.

**Comment by WinterMute** [comment]
fixed with release 47
