### ISSUE TITLE
need old version of devkitPro

### ISSUE THREAD

**Issue by fre4kyC0de** [devkitPro/buildscripts#29]
Dear devkitPro-team,

due to two hard drive failures I lost my installed copy of devkitPro. In my archive I found a copy of devkitARM r45 and devkitPPC r28.
My problem is, that some of my projects (including my own build of mocha) fail to build with the most recent version (from a new setup) and also with my archived copy.
As I currently want to apply a modification to some of the projects and don‘t have the time to fix my development environment to work with the new devkitPro until I need the new build, I wanted to ask , if you still have a copy of 
- devkitPPC r29 / r29-1
- devkitARM r46 / r47
for Windows, you can send to me (as your sourceforge repo is down, I can‘t download from there).

Thank you in advance

**Comment by WinterMute** [comment]
devkitPro is an organisation dedicated to producing tools and libraries for homebrew game console development. It has no versions.

We don't provide old binaries of tools.

**Comment by Leseratte10** [comment]
@fre4kyC0de If this is still relevant half a year later, many old versions can be found in my archive: https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/
