### ISSUE TITLE
Mixing std::cout and printf fails to run on 3DS hardware

### ISSUE THREAD

**Issue by neobrain** [devkitPro/buildscripts#3]
Mixing `std::cout` and printf should work fine as far as I know, yet it makes 3DS applications crash.

For example, take ctrulib's graphics/printing/hello-world example, and the line `std::cout << "test" << std::endl;` after the second printf, so that you end up with

```
    printf("\x1b[15;19HHello World!");

    printf("\x1b[29;15HPress Start to exit.");

    std::cout << "test" << std::endl;
```

Of course, the file `main.c` should also be renamed to `main.cpp` to compile this as C++ code. It can be observed that this code crashes, while it works when commenting out either the `std::cout` line or the two `printf` lines.

NOTE: I already tried explicitly setting `std::cout.sync_with_stdio(true);`, which didn't help unfortunately.

~~NOTE2: This issue can be reproduced when running the application in Citra.~~

**Comment by WinterMute** [comment]
Is this still an issue for you? I could never reproduce this

**Comment by WinterMute** [comment]
closing as not reproducible.
