### ISSUE TITLE
C++ Exceptions cause the console to freeze with dkA64, with no output

### ISSUE THREAD

**Issue by Adubbz** [devkitPro/buildscripts#30]
``-fno-exceptions`` has been removed from the Makefile, simply throwing any exception should be sufficient to cause this. I reproduced this bug on 5.1.0, after @rajkosto noted similar experiences in IRC.

Here is the code I used:
```
    try
    {
        throw std::runtime_error("Test error");
    }
    catch (std::exception& e)
    {

    }
```

Running the homebrew as an NSO also has the same issue, however only the app freezes rather than the entire console. There is still no output however.

**Comment by nwert** [comment]
This is now fixed with latest devkitA64 r12.

**Comment by neobrain** [comment]
@nwert Hey, that's awesome! Do you happen to know what change fixed this issue?

**Comment by nwert** [comment]
Missing '.eh_frame' in libgcc resulted in '_Unwind_RaiseException' aborting; unwind metadata is generated per default now.

**Comment by neobrain** [comment]
Ah, I see. Thanks for the info :)
