### ISSUE TITLE
Fail to extract "-.tar"

### ISSUE THREAD

**Issue by ParzivalWolfram** [devkitPro/buildscripts#38]
```
sh build-devkit.sh
Please note, these scripts are provided as a courtesy, toolchains built with them
are for personal use only and may not be distributed by entities other than devkitPro.
See http://devkitpro.org/wiki/Trademarks

Users should use devkitPro pacman to maintain toolchain installations where possible
See https://devkitpro.org/wiki/devkitPro_pacman

Patches and improvements are of course welcome, please submit a PR
https://github.com/devkitPro/buildscripts/pulls

build-devkit.sh: 70: build-devkit.sh: function: not found
extracting -
tar: /-.tar.: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error extracting
```
I'm on Linux Mint, so no pacman for meeeeeeeeeeeeeeeeeeee
(Fine with me, i'm not installing another package manager JUST FOR YOU)

**Comment by fincs** [comment]
Please read https://devkitpro.org/wiki/devkitPro_pacman
We have standardised on pacman, we use it on all OSes we support (that includes Windows, Linux and Mac). We provide a special compiled version of pacman for Debian based Linux distros (that includes Linux Mint) which you can install right away.
I think you will agree with me in that providing separate versions of packages for every single package manager under the sun is a pretty stupid idea.

**Comment by ParzivalWolfram** [comment]
LITERALLY EVERYONE ELSE DOES THAT.

You could just... help with the issue, maybe?
