### ISSUE TITLE
Linux installation for user

### ISSUE THREAD

**Issue by AZO234** [devkitPro/buildscripts#39]
Please consider a method that does not require SU authority to install in Linux user area.

I tried to change follows, I could install with user authority only.

- buildscripts/build-devkit.sh

[from]
if [ ! -z "$BUILD_DKPRO_INSTALLDIR" ] ; then
	INSTALLDIR="$BUILD_DKPRO_INSTALLDIR"
else
	echo
...
	read -e INSTALLDIR
	echo
fi

[to]
if [ ! -z "$BUILD_DKPRO_INSTALLDIR" ] ; then
	export INSTALLDIR="$BUILD_DKPRO_INSTALLDIR"
else
	echo
...
	read -e INSTALLDIRH
	export INSTALLDIR="$INSTALLDIRH"
	echo
fi

- devkitarm-crtls-1.0.0.tar.xz/Makefile

[from]
install: all
	@mkdir -p $(DESTDIR)/opt/devkitpro/devkitARM/arm-none-eabi/lib
	@cp -v *.specs *.ld *.mem $(DESTDIR)/opt/devkitpro/devkitARM/arm-none-eabi/lib
	@cp -rv thumb armv6k *.o $(DESTDIR)/opt/devkitpro/devkitARM/arm-none-eabi/lib

[to]
install: all
	@mkdir -p $(INSTALLDIR)/devkitARM/arm-none-eabi/lib
	@cp -v *.specs *.ld *.mem $(INSTALLDIR)/devkitARM/arm-none-eabi/lib
	@cp -rv thumb armv6k *.o $(INSTALLDIR)/devkitARM/arm-none-eabi/lib

- devkitarm-rules-1.0.0.tar.xz/Makefile

[from]
install:
	@mkdir -p $(DESTDIR)/opt/devkitpro/devkitARM
	@cp -v $(FILES) $(DESTDIR)/opt/devkitpro/devkitARM

[to]
install:
	@mkdir -p $(INSTALLDIR)/devkitARM
	@cp -v $(FILES) $(INSTALLDIR)/devkitARM

- devkitppc-rules-1.0.0.tar.xz/Makefile

[from]
install:
	@cp -v $(FILES) $(DESTDIR)/opt/devkitpro/devkitPPC

[to]
install:
	@cp -v $(FILES) $(INSTALLDIR)/devkitPPC

Regards.

**Comment by WinterMute** [comment]
We don't really support use of the buildscripts by end users, where possible you should use [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman).

If you really don't have the option to use pacman & the official binaries you miss out on the rest of the infrastructure & the portlibs.
