### ISSUE TITLE
Installing devkitPro in Ubuntu

### ISSUE THREAD

**Issue by yerAWeeGit** [devkitPro/buildscripts#44]
Please note: recommended and supported installation of the toolchains on Ubuntu is with [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman)

_Originally posted by @WinterMute in https://github.com/devkitPro/buildscripts/issues/43#issuecomment-493205655_

I'm aware of that and have already installed the groups I am interested in using pacman - `nds-dev` and `3ds-dev`. It seems there is more to it than this which is why I'm trying to build `buildscripts`. Unless there's another way of going about this? I've tried compiling the NDS Hello World example using `g++` but it fails to find `nds.h`.

**Comment by fincs** [comment]
We provide cross compilers for all the platforms we support. Both the nds-dev and 3ds-dev groups should have installed devkitARM. Is there any error happening when you run `make` in the folder for the [hello world example](https://github.com/devkitPro/nds-examples/tree/master/hello_world)?

**Comment by yerAWeeGit** [comment]
Turns out I'm just dumb and hadn't tried using `make` in the example. I've not tried running the produced file but it's certainly compiled. You can close this.

**Comment by fincs** [comment]
Also, for reference, devkitPro is not the name of any piece of software. It's the name of our organization, which produces several products including but not limited to devkitARM and libnds (which are used for DS development).
