### ISSUE TITLE
libnx 2.2.0 bz2 unavailable

### ISSUE THREAD

**Issue by switchjsdev** [devkitPro/buildscripts#45]
setting `LIBNX_VER=2.2.0` attempts to download https://downloads.devkitpro.org/libnx-src-2.2.0.tar.bz2 which 404s.  Probably related: libnx 2.2.0 release has no bz2 asset https://github.com/switchbrew/libnx/releases/tag/v2.2.0

**Comment by WinterMute** [comment]
Scripts no longer provide libraries. Ideally you should be using [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman) to install & maintain your toolchain installation.
