### ISSUE TITLE
Include rules in build

### ISSUE THREAD

**Issue by mid-kid** [devkitPro/buildscripts#46]
Recently, the building of the libraries was removed from these buildscripts.
However, with them, the installation of the makefile rules was removed as well.
These rules, while easy to install manually, are an integral part of how this toolchain functions, as even without the "core" libraries, these are necessary to build anything with this toolchain.
They're still being downloaded in the buildscript, just never used.

Please consider including them in these buildscripts again, for the people building a minimal version of the toolchain on their own.

(And while you're at it, could you make the Makefile respect the PREFIX variable?)

**Comment by WinterMute** [comment]
We don't really want to support manual building of the tools to non-standard prefixes. It would be great if you could use pacman to manage your toolchain install & stick with the stock prefix - it helps avoid all kinds of unnecessary support issues.

Bear in mind that people copy what they see others doing even if it makes no sense for them to do. Not having 100s of people recompile binaries for no reason will also help reduce energy consumption and potentially help mitigate climate change.

**Comment by mid-kid** [comment]
I've been building this toolchain from source for years, and prefer continuing to do so, mainly because I'm not comfortable having multiple package managers managing a single prefix. I'm aware this is an unsupported setup and make sure to test the official methods before reporting bugs. I as such never "show" this to people or tell them how to do things like this - I want them to avoid the potential problems from running an unsupported setup.

When I referred to "the people building ..." I was mostly assuming there's possibly others that run a setup like this, or would like to use these scripts for any reason including but not limited to running it on unsupported platforms like BSD. Just to clarify: I am not implying you should support setups like this.

However, what I am suggesting is that a recent removal from these build scripts makes the toolchain, as built by these scripts, ultimately incomplete. While I understand the shift towards pacman and I know the additional files can be installed manually, there's a bit of a discrepancy with how the scripts still fetch and build a bunch of outdated tools yet don't include some of the more "core" parts of the toolchain. I think it's worth maintaining these scripts in a usable state, even if their use isn't supported.

That, or actually deprecate the unmaintained/unused parts of these scripts, to avoid any misconceptions as to what they're supposed to do.

If you don't think this is something worth solving, feel free to close the issue. This is merely an improvement suggestion, not a support request.

**Comment by WinterMute** [comment]
Added the rules files installation back quite some time ago & forgot to close this, sorry. https://github.com/devkitPro/buildscripts/commit/9165c280f374f3998e100d4a5ea4d15c615facd3
