### ISSUE TITLE
return value uninitialized in utimes

### ISSUE THREAD

**Issue by mtheall** [devkitPro/buildscripts#49]
https://github.com/devkitPro/buildscripts/blob/0add4d1b5ced63f9b278de7a3ebf4644df6c30b4/dka64/patches/newlib-3.1.0.patch#L8592-L8594
https://github.com/devkitPro/buildscripts/blob/57ec7b67acb7b32e9bbbb7e3d9ebb0c6f16219c8/dkppc/patches/newlib-3.3.0.patch#L7169-L7171
https://github.com/devkitPro/buildscripts/blob/736db33e06f94121969562cafe3ad8613bda43c3/dkarm-eabi/patches/newlib-3.1.0.patch#L7261-L7263

**Comment by WinterMute** [comment]
Fixed with updated patchsets
