### ISSUE TITLE
Latest devkitPPC GCC Regression

### ISSUE THREAD

**Issue by PsiLupan** [devkitPro/buildscripts#50]
Have a large project that prior to updating to the latest devkitPro release today from what was presumably GCC 8.2.0, I began experiencing a graphical regression related to the colors when compiling with GCC after updating. 

My project has branch for GCC and another branch for Clang that I regularly switch between, and the issue is not present for Clang. As a result, I don't suspect it's an issue with libogc itself - but it's hard to narrow down. 

I also tested on a Gamecube, and it outright crashes to the stack trace rather than displaying as Dolphin does. Unfortunately, I can't really show that, since my capture card is in a box somewhere and the TV itself is unreadable. This crash not occur for Clang, which renders on a Gamecube correctly.

Not sure I can really come up with a test case here, but figured I'd make note of it in case someone else runs into this.

GCC:
![GCCBug](https://user-images.githubusercontent.com/7443598/85464488-4f9d6800-b56d-11ea-8e4a-bb94b8a9d844.png)

Clang:
![ClangNoBug](https://user-images.githubusercontent.com/7443598/85464468-48765a00-b56d-11ea-8141-1932a10214a9.png)

**Comment by WinterMute** [comment]
Also moved this to the buildscripts repo where we currently manage the tools. It's not a libogc issue.

This is also likely to be closed pending an actual testcase that shows an actual bug. Working when built with one compiler and not working when built with another compiler (whether that be a different gcc version or clang or any other random compiler you have access to) isn't necessarily an indication of any fault with the compiler.

**Comment by PsiLupan** [comment]
> Turning that warning back on and adding -Wall I get a lot of warnings that really should be fixed. Implicit function definitions and may be used uninitialized are classic nasal demon triggers.
> 
> [build.log](https://github.com/devkitPro/libogc/files/4824141/build.log)
> 
> I would be massively unsurprised if fixing all those warnings made the issue go away. Can't guarantee it will but I've seen far too many problems "magically fixed" by simply fixing warnings.

Cleaned up nearly all the warnings, save for some in some unused functions. Also, specifically checked a known use of an uninitialized value for the tev coloring that the game itself does, and that didn't appear to be the culprit either.

It's not likely I'll be able to come up with a test case anytime soon, so I guess I'll go ahead and close this. I'll try to get the stack trace at some point and see where it happens. If it's in libogc, I'll bring the issue back there with more details on the nature of that.
