### ISSUE TITLE
Missing source archives

### ISSUE THREAD

**Issue by bitscher** [devkitPro/buildscripts#52]
The following archives seem to be missing:
- binutils-2.34.tar.xz
- gcc-10.2.0.tar.xz

```
$ curl -f -L -O https://downloads.devkitpro.org/binutils-2.34.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   272    0   272    0     0    425      0 --:--:-- --:--:-- --:--:--   425
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
$ curl -f -L -O https://downloads.devkitpro.org/gcc-10.2.0.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   269    0   269    0     0    419      0 --:--:-- --:--:-- --:--:--   419
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

Workaround: Manually download them from GNU before running `build-devkit.sh`

**Comment by bitscher** [comment]
Same issue as #51 

Since you will likely ask what I'm trying to achieve.
I tried building Swiss from source to be met by a missing symbol in libogc, which lead me to attempt to build the libogc in emukidid's repo (https://github.com/emukidid/libogc) with the latest devkitppc installed:
```
$ pacman -Q
devkit-env 1.0.1-2
devkitPPC r38-1
devkitPPC-gdb 9.2-1
devkitppc-rules 1.1.0-1
devkitpro-keyring 20180316-1
gamecube-examples 20200609-1
gamecube-pkg-config 0.28-5
gamecube-tools 1.0.2-1
general-tools 1.2.0-2
libfat-ogc 1.1.5-2
libogc 2.1.0-1
ppc-pkg-config 0.28-5
```

But I'm getting a compilation error on `libogc/system.c`
```
system.c
/home/bitscher/outsrc/libogc/libogc/system.c: In function '__init_syscall_array':
/home/bitscher/outsrc/libogc/libogc/system.c:296:2: error: '__syscalls' undeclared (first use in this function); did you mean '__syscall_exit'?
  296 |  __syscalls.sbrk_r = __libogc_sbrk_r;
      |  ^~~~~~~~~~
      |  __syscall_exit
```
Turns out that `__syscalls` is not defined in `/opt/devkitpro/devkitPPC/powerpc-eabi/include/sys/iosupport.h` so I was probing a little.

**Comment by bitscher** [comment]
On the positive side I found the culprit: https://github.com/devkitPro/buildscripts/commit/5e720e01c1db3cfa2366b0b22ef9a54e8f9f64e6#diff-4472ef54bed31eb07266349cf6821994
I suppose using an older version of devkitppc will work until the lib is fixed.

**Comment by WinterMute** [comment]
Please do not use either old versions of the tools or build random libogc forks in order to "fix" code that should build with stock components. You should report an issue with Swiss and ask that code is upstreamed rather than having incompatible forks.

**Comment by bitscher** [comment]
The reported issue was not about a fork of libogc not building, it was about the build scripts of devkitpro failing because of missing source archives.

**Comment by WinterMute** [comment]
We discourage end users from building the tools and prefer that everything is managed via [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman). This would help to ensure that people can actually build each other's projects if certain people didn't insist on not upstreaming code. We cannot guarantee that tools you build yourself will function properly and provide no support for self built tools or building from source.

We especially don't provide support for incompatible forks of our code.
