### ISSUE TITLE
Single threaded libstdc++

### ISSUE THREAD

**Issue by FrankHB** [devkitPro/buildscripts#6]
Since the thread model is "single thread" for devkitARM, is `-fno-threadsafe-statics` suitable for libstdc++ configure command line?

**Comment by WinterMute** [comment]
No. We support threading on 3DS.

**Comment by FrankHB** [comment]
That's a bit strange. Is the standard library facilities for threading available?
And is it possible to support threading on DS as well?

**Comment by WinterMute** [comment]
Currently, no. Standard library facilities for threading are not available. Whether they are or not depends on the feasibility of providing a pthreads API which may or may not happen any time soon.

I'm not sure that threading on DS makes any sense really.

In any case, I have no plans to arbitarily remove things on the basis of not being currently useful.

**Comment by FrankHB** [comment]
I see.

Though not confirmed, I heard Nintendo has threading support for DS in their SDK.
