### ISSUE TITLE
404 from `downloads.devkitpro.org`

### ISSUE THREAD

**Issue by YoshiRulz** [devkitPro/buildscripts#63]
### What's the issue you encountered?

I'm running [`build-devkit.sh` from the `devkitARM_r64` tag](https://github.com/devkitPro/buildscripts/blob/devkitARM_r64/build-devkit.sh) and it fails due to a network error: `curl -f -L -O https://downloads.devkitpro.org/gcc-14.1.0.tar.xz` gets a 404 response from the server.
(I'm actually trying to get the thing building in the Nix sandbox, but for the purposes of this issue that's not relevant—[the link](https://downloads.devkitpro.org/gcc-14.1.0.tar.xz) is dead outside of the sandbox too.)

### How can the issue be reproduced?

```
curl -f -L -O https://downloads.devkitpro.org/gcc-14.1.0.tar.xz
```

### Environment?

NixOS

### Additional context?

N/A

**Comment by mjsir911** [comment]
I'm seeing the same issue
