### ISSUE TITLE
dkpsp: Incorrect COMPILER_PATH

### ISSUE THREAD

**Issue by 173210** [devkitPro/buildscripts#7]
`c:/devkitpro/devkitpsp/bin/../libexec/gcc/psp/4.6.2/` is duplicated, and `c:/devkitpro/devkitpsp/bin` is not includes, thus collect2 can't find tools.
It disables to build https://github.com/173210/valentine-hbl.git, which invokes ld via GCC to use lto plugin.
The bug is confirmed on Windows, but not on Ubuntu.
```
COMPILER_PATH=c:/devkitpro/devkitpsp/lib/gcc/../../libexec/gcc/psp/4.6.2/;c:/devkitpro/devkitpsp/lib/gcc/../../libexec/gcc/;c:/devkitpro/devkitpsp/bin/../libexec/gcc/psp/4.6.2/;c:/devkitpro/devkitpsp/bin/../libexec/gcc/psp/4.6.2/;c:/devkitpro/devkitpsp/bin/../libexec/gcc/;c:/devkitpro/devkitpsp/bin/../lib/gcc/psp/4.6.2/../../../../psp/bin/;c:/devkitpro/devkitpsp/bin/../lib/gcc/psp/4.6.2/../../../../psp/bin/
```

**Comment by WinterMute** [comment]
devkitPSP is no longer being maintained, sorry.

**Comment by 173210** [comment]
But you have no removed it from the repository yet. Can I make a pull request to fix this bug and update toolchains?
